import type {
  RibbonTheme,
  RibbonThemeColorScheme,
  RibbonThemeId,
  RibbonThemeTokens,
} from './ThemeProvider.types';

const fontFamily =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

function defineTheme(
  id: RibbonThemeId,
  label: string,
  colorScheme: RibbonThemeColorScheme,
  tokens: RibbonThemeTokens,
): RibbonTheme {
  return Object.freeze({ colorScheme, id, label, tokens: Object.freeze(tokens) });
}

const modernLight = defineTheme('modern-light', 'Light', 'light', {
  accent: '#4473ca',
  accentHover: '#2a5bb9',
  borderControl: '#e1e1e1',
  borderControlHover: '#b9b9b9',
  borderDivider: '#eaeaea',
  borderPopover: '#cfcfcf',
  borderToolbar: '#cbcbcb',
  brandLogo: '#ff6f3d',
  controlHover: '#eaeaea',
  controlPressed: '#e1e1e1',
  controlSelected: '#cfdcf3',
  controlSelectedText: '#2a5bb9',
  fontFamily,
  headerControlHover: '#eaeaea',
  headerControlPressed: '#e1e1e1',
  iconDefault: 'rgba(0, 0, 0, 0.66)',
  iconStrong: 'rgba(0, 0, 0, 0.8)',
  radiusSmall: '3px',
  scrollbarThumb: '#c4c4c4',
  selection: '#3494fb',
  shadowPopover: 'rgba(0, 0, 0, 0.18)',
  surfaceCanvas: '#e6e6e6',
  surfaceContent: '#ffffff',
  surfaceHeader: '#f3f3f3',
  surfaceInput: '#ffffff',
  surfacePanel: '#f3f3f3',
  surfacePopover: '#ffffff',
  surfaceTabActive: '#ffffff',
  surfaceTabBar: '#f3f3f3',
  surfaceToolbar: '#ffffff',
  surfaceToolbarSubtle: '#efefef',
  tabIndicator: '#444444',
  textHeader: 'rgba(0, 0, 0, 0.8)',
  textInverse: '#ffffff',
  textLink: '#445799',
  textPrimary: 'rgba(0, 0, 0, 0.8)',
  textSecondary: 'rgba(0, 0, 0, 0.6)',
  textTertiary: 'rgba(0, 0, 0, 0.4)',
});

const modernDark = defineTheme('modern-dark', 'Dark', 'dark', {
  accent: '#4a7be0',
  accentHover: '#366cda',
  borderControl: '#5b5b5b',
  borderControlHover: '#7a7a7a',
  borderDivider: '#555555',
  borderPopover: '#5b5b5b',
  borderToolbar: '#585858',
  brandLogo: '#ff7a4d',
  controlHover: '#585858',
  controlPressed: '#686868',
  controlSelected: '#2c4677',
  controlSelectedText: '#ffffff',
  fontFamily,
  headerControlHover: '#585858',
  headerControlPressed: '#686868',
  iconDefault: '#d4d4d4',
  iconStrong: '#f3f3f3',
  radiusSmall: '3px',
  scrollbarThumb: '#6a6a6a',
  selection: '#3494fb',
  shadowPopover: 'rgba(0, 0, 0, 0.5)',
  surfaceCanvas: '#262626',
  surfaceContent: '#ffffff',
  surfaceHeader: '#222222',
  surfaceInput: '#2a2a2a',
  surfacePanel: '#222222',
  surfacePopover: '#404040',
  surfaceTabActive: '#404040',
  surfaceTabBar: '#222222',
  surfaceToolbar: '#404040',
  surfaceToolbarSubtle: '#404040',
  tabIndicator: '#f3f3f3',
  textHeader: '#f3f3f3',
  textInverse: '#222222',
  textLink: '#92b7f0',
  textPrimary: '#f3f3f3',
  textSecondary: '#cecece',
  textTertiary: '#b2b2b2',
});

const classicLight = defineTheme('classic-light', 'Classic Light', 'light', {
  accent: '#446995',
  accentHover: '#365279',
  borderControl: '#cfcfcf',
  borderControlHover: '#aeaeae',
  borderDivider: '#e0e0e0',
  borderPopover: '#c4c4c4',
  borderToolbar: '#cbcbcb',
  brandLogo: '#ffffff',
  controlHover: '#d8dadc',
  controlPressed: '#c4c7ca',
  controlSelected: '#c5d4e8',
  controlSelectedText: '#2f527d',
  fontFamily,
  headerControlHover: 'rgba(0, 0, 0, 0.15)',
  headerControlPressed: 'rgba(0, 0, 0, 0.25)',
  iconDefault: '#5a5a5a',
  iconStrong: '#444444',
  radiusSmall: '3px',
  scrollbarThumb: '#bcbcbc',
  selection: '#3494fb',
  shadowPopover: 'rgba(0, 0, 0, 0.2)',
  surfaceCanvas: '#e2e2e2',
  surfaceContent: '#ffffff',
  surfaceHeader: '#446995',
  surfaceInput: '#ffffff',
  surfacePanel: '#f1f1f1',
  surfacePopover: '#f7f7f7',
  surfaceTabActive: '#f1f1f1',
  surfaceTabBar: '#446995',
  surfaceToolbar: '#f1f1f1',
  surfaceToolbarSubtle: '#f1f1f1',
  tabIndicator: '#446995',
  textHeader: '#ffffff',
  textInverse: '#ffffff',
  textLink: '#445799',
  textPrimary: '#444444',
  textSecondary: '#757575',
  textTertiary: '#a0a0a0',
});

const themes: Readonly<Record<RibbonThemeId, RibbonTheme>> = Object.freeze({
  'classic-light': classicLight,
  'modern-dark': modernDark,
  'modern-light': modernLight,
});

export const ribbonThemeIds: readonly RibbonThemeId[] = Object.freeze([
  'modern-light',
  'classic-light',
  'modern-dark',
]);

export function getRibbonTheme(themeId: RibbonThemeId): RibbonTheme {
  return themes[themeId];
}
